<?php declare(strict_types=1); ?>
<div class="modal fade" tabindex="-1" role="dialog" id="preflightModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Performing preflight checks</h4>
            </div>
            <div class="modal-body">
                <?php /*
                <p class="test">Verifying mail transport</p>
                <p class="result warning">No mail configured</p>
                <p class="test">Checking repository directory permissions</p>
                <p class="result error">Cannot access repository directory</p>
                */ ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" disabled>Close</button>
                <button type="submit" class="btn btn-danger" disabled>Save changes</button>
            </div>
        </div>
    </div>
</div>
