<?php declare(strict_types=1); ?>
<div class="subheader">
    <h1>Dashboard</h1>
    <ul class="actions">
        <li><button class="btn btn-default"><i class="fa fa-fw fa-plus-square"></i> New project</button></li>
        <li><button class="btn btn-danger"><i class="fa fa-fw fa-warning"></i> Delete project</button></li>
    </ul>
</div>
<div id="main-content" class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <h1>Dashboard</h1>
        </div>
    </div>
</div>
